### ISSUE TITLE
Frontend Design Pattern 정하기

### ISSUE THREAD

**Issue by zoomKoding** [woowa-techcamp-2020/market-8#1]
[아토믹 디자인 패턴 레퍼런스](https://brunch.co.kr/@ultra0034/63)

React를 사용하지 않고도 Atomic Design Pattern을 적용해볼 수 있을까요?
이전에 Todo에 vanilla로 도전해본 적이 있는데 이번 프로젝트에 적용시켜보고 싶습니다!
[아토믹 패턴 연습 레파지토리](https://github.com/zoomKoding/vanilla-javascript-practice/tree/solution/zoomkoding)

**Comment by myungwoo-Y** [comment]
[리액트에 아토믹 디자인 적용하기](https://github.com/danilowoz/react-atomic-design/blob/master/src/components/atoms/button/index.js)

위 예를 보면 아토믹 디자인을 적용하기 위해서는 JavaScript내에서 html을 렌더하는 기능이 추가해야 할 것 같아요.

[Vanilla JS 를 React.js 처럼 사용하기](https://velog.io/@pandati0710/Vanilla-Js%EB%A1%9C-react%EB%9E%91-%EB%B9%84%EC%8A%B7%ED%95%98%EA%B2%8C-%EC%BD%94%EB%94%A9%ED%95%98%EA%B8%B0)

예처럼 Vanilla JS를 React.js처럼 쓸수 있게 만들어 아토믹을 적용할 요소들을 컴포넌트화 하면 사용 할 수 있을것 같아요!
위 예는 모두 클레스로 구성되어있는데 요구사항 대로 함수로 변경하는 작업이 좀 필요할것 같고요!

**Comment by zoomKoding** [comment]
생각보다 시간이 많이 걸릴 수도 있을 것 같은데 Vanilla.js를 React.js처럼 컴포넌트화하는 과정도 많은 배움이 있을까요? 
그리고 아토믹 패턴에 대해서는 혹시 어떻게 생각하시나요? @crongro

**Comment by zoomKoding** [comment]
[리액트 to 바닐라 블로그 글](https://medium.com/hackernoon/how-i-converted-my-react-app-to-vanillajs-and-whether-or-not-it-was-a-terrible-idea-4b14b1b2faff)을 참고하면 좋을 것 같습니다!
