### ISSUE TITLE
Vanilla JS로 Component 구현하기

### ISSUE THREAD

**Issue by zoomKoding** [woowa-techcamp-2020/market-8#7]
Atomic Design을 도전해보기 위해 React Component와 유사하게 Vanilla로 구현해보기

### 레퍼런스
[리액트 to 바닐라 블로그 글](https://medium.com/hackernoon/how-i-converted-my-react-app-to-vanillajs-and-whether-or-not-it-was-a-terrible-idea-4b14b1b2faff)

**Comment by myungwoo-Y** [comment]
오! 리액트처럼 중첩해서 컴포넌트 생성도 가능 할 것 같네요!
쉽게 atomic design pattern 구현 할 수 있겠네요! 👍👍
